<?= $this->extend('layout/main') ?>
<?= $this->section('content') ?>

<?php if (empty($reports)): ?>
<div class="text-center py-5">
    <i class="bi bi-file-earmark-x" style="font-size:3rem; color:#cbd5e1"></i>
    <h5 class="mt-3 text-muted">No reports available yet</h5>
    <p class="text-muted">Run the AI analysis first to generate reports.</p>
    <a href="<?= base_url('analysis') ?>" class="btn btn-primary">
        <i class="bi bi-cpu"></i> Go to Analysis
    </a>
</div>

<?php else: ?>

<?php
    $catColors = [
        'academic_performance'    => ['bg' => '#ede9fe', 'text' => '#7c3aed', 'badge' => 'primary'],
        'completion_tracking'     => ['bg' => '#dcfce7', 'text' => '#16a34a', 'badge' => 'success'],
        'enrollment_demographics' => ['bg' => '#dbeafe', 'text' => '#2563eb', 'badge' => 'info'],
        'subject_analysis'        => ['bg' => '#fef9c3', 'text' => '#ca8a04', 'badge' => 'warning'],
        'student_drilldown'       => ['bg' => '#e2e8f0', 'text' => '#1e293b', 'badge' => 'dark'],
    ];
    $chartIcons = [
        'bar'      => 'bi-bar-chart-fill',
        'line'     => 'bi-graph-up',
        'pie'      => 'bi-pie-chart-fill',
        'doughnut' => 'bi-circle-half',
        'scatter'  => 'bi-diagram-3-fill',
    ];
?>

<div class="d-flex align-items-center justify-content-between mb-4">
    <div>
        <h5 class="fw-semibold mb-0">All Reports</h5>
        <span class="text-muted small"><?= count($reports) ?> reports generated by AI analysis</span>
    </div>
    <a href="<?= base_url('analysis') ?>" class="btn btn-sm btn-outline-secondary">
        <i class="bi bi-cpu"></i> Manage Analysis
    </a>
</div>

<div class="row g-3">
    <?php foreach ($reports as $r): ?>
    <?php
        $colors = $catColors[$r['category']] ?? ['bg' => '#f1f5f9', 'text' => '#475569', 'badge' => 'secondary'];
        $icon   = $chartIcons[$r['chart_type']] ?? 'bi-bar-chart';
    ?>
    <div class="col-md-6 col-xl-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-body">
                <div class="d-flex align-items-start justify-content-between mb-2">
                    <div class="kpi-icon mb-2"
                         style="background:<?= $colors['bg'] ?>; width:40px; height:40px; font-size:1.1rem">
                        <i class="bi <?= esc($icon) ?>" style="color:<?= $colors['text'] ?>"></i>
                    </div>
                    <span class="badge bg-<?= $colors['badge'] ?> badge-category">
                        <?= esc(str_replace('_', ' ', $r['category'])) ?>
                    </span>
                </div>
                <h6 class="fw-semibold mb-1"><?= esc($r['title']) ?></h6>
                <p class="text-muted small mb-3"><?= esc($r['description']) ?></p>
                <div class="text-muted small">
                    <i class="bi bi-bar-chart"></i> <?= esc($r['chart_type']) ?> chart
                </div>
            </div>
            <div class="card-footer bg-white border-top-0">
                <div class="d-flex gap-2">
                    <a href="<?= base_url('reports/' . esc($r['report_id'])) ?>" class="btn btn-sm btn-primary flex-grow-1">
                        <i class="bi bi-eye"></i> View Report
                    </a>
                    <a href="<?= base_url('reports/pdf/' . esc($r['report_id'])) ?>" class="btn btn-sm btn-outline-secondary">
                        <i class="bi bi-file-pdf"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<?= $this->endSection() ?>
